[theme]
primaryColor = "#005cab"          # Main accent color (buttons, widgets, etc.)
backgroundColor = "#f5f5f5"       # Background color for the app
secondaryBackgroundColor = "#ffffff" # Background color for containers
textColor = "#333333"             # Default text color
font = "sans serif"               # Choose from available fonts: "sans serif", "serif", "monospace"
